---
- hosts: all
  remote_user: steveb
  tasks:

  - name: Add EPEL repository
    yum_repository:
      name: epel
      description: EPEL YUM repo
      file: epel.repo
      baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/

  - name: Install nano
    yum:
      name: nano
      state: latest

  - name: Install htop
    yum:
      name: htop
      state: latest

